# サイト基本設定
title: "Tomoya Nakayama"
locale: "ja-JP"
permalink: /:categories/:title/

# テーマの設定（GitHub Pages標準対応形式）
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# プロフィール欄（左側）の設定
author:
  name: "中山 友哉"
  bio: "メダカをモデルとした動物の季節・温度適応"
  links:
    - label: "researchmap"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://researchmap.jp/nakayama.t"

# 独自のビルド設定を無視するための設定
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
